name: "toyo-tomi's Action in Action"
description: "Greets someone and always returns 42"
inputs:
  who-to-greet: # id on the input
    description: "Who to greet"
    required: true
    default: "World"

outputs:
  answer: # id of the output
    description: "The answer to everything (always 42)"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
